---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: patrick2029
    group_name: devops
  vars_files:
    - variables.yml

  tasks:
    - name: Check the time
      command: datemdhftysbdf
#      when: ansible_distribution == "patrick" or ansible_processor_nproc == 2
    - name: create user patrick
      user:
          name: "{{user_name}}"
          comment: Patrick Admin
    - name:  create group
      group:
          name: "{{group_name}}"
          state: present
    - name: install package
      package:
          name: "{{pkg_name}}"
          state: present